#include <stdio.h>

int main(){

  // What C does wen you #include a file is that it copies all the contents of said file onto the top of your code file
  // This may cause certain problems sometimes
  // One of these problems is that if two files include the same header
  // And if both these files are included somewhere else, then we may end up with a lot of nasty errors
  // due to the fact that some functions and structs get redefined
  // (C doesn't like when you define things twice as then it doesn't know what to pick)
  // One of the most practical ways to solve this is using #pragma once

  // #pragma once
  // Typing #pragma once at the top of a header file ensures that that header file will only get included once in the case
  // that a sequence of events leads to the scenario mentioned above

  // HEADER GUARDS are the older way to solve this problem of multiple inclusions
  // They are also known as include guards
  // This is the older way to do things
  /* SYNTAX:
   
    #ifndef MY_HEADER_H
    #define MY_HEADER_H

    // declarations go here

    #endif
  
  */


  // Above code means: if this header hasn't been included yet, then include it, if it has, then skip it.

  /*

  CODE EXAMPLE  (Generated by ChatGPT):

  In math_utils.h:

  #ifndef MATH_UTILS_H
  #define MATH_UTILS_H

  int add(int a, int b);

  #endif

  In math_utils.c:

  #include <stdio.h>
  #include "math_utils.h"
  #include "math_utils.h"   // included twice on purpose

  int main(void) {
    printf("%d\n", add(2, 3));
    return 0;
  }

  In main.c:

  #include <stdio.h>
  #include "math_utils.h"
  #include "math_utils.h"   // included twice on purpose

  int main(void) {
      printf("%d\n", add(2, 3));
      return 0;
  }

  What this means:

  math_utils.h is included twice

  The guard:

    #ifndef MATH_UTILS_H
    #define MATH_UTILS_H


  ensures the contents are only processed once

  Program compiles and links correctly
  */

  // However, #pragma once, is now accepted by most compilers and should be the option you should generally stick with
  //as it is easier and more or less the convention nowadays

  return 0;
}